### PR TITLE
cast class indices to float before torch.gather for onnx export

### PR DESCRIPTION
**Pull request by bchiu**

### CODE REVIEW

**Comment by developer0hye** [comment]
@bchiu I reviewed your code, please check it!

**Comment by bchiu** [comment]
Looks good to go! Do you have any plans to add 3D tracking and nuscenes dataset? 

Btw, the torch model is still faster than onnx with "flip" turned off (50fps on my machine)

**Comment by developer0hye** [comment]
@bchiu Okay, I will merge this pull request at night today.

**Comment by developer0hye** [comment]
@bchiu I actually... I **had** no plan to add 3d tracking and nuscenes dataset. But I am interested in these things. I wanted to expand from my areas 2D detection task to other tasks like 3D tracking or pose estimation.

**Comment by bchiu** [comment]
i am going to try quantizing the onnx model to tflite and run it on edgetpu. let you know how it goes. cheers :)

**Comment by developer0hye** [comment]
@bchiu Thanks! Cheer up!

**Pull request merged**
